const mongoose = require("mongoose");

const subscriptionSchema = new mongoose.Schema({
  // 🔗 LINKS
  club: { type: mongoose.Schema.Types.ObjectId, ref: "Club", required: true },
  year: { type: mongoose.Schema.Types.ObjectId, ref: "FestivalYear", required: true },
  user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },

  // 💰 AGGREGATE DATA (For fast dashboards)
  totalPaid: { type: Number, default: 0 },
  totalDue: { type: Number, default: 0 },
  
  // 🚀 DYNAMIC SLOTS
  // This array is generated by the utility above
  installments: [
    {
      index: { type: Number, required: true }, 
      label: { type: String }, // "Week 1" or "Jan"
      amountExpected: { type: Number, default: 0 },
      
      isPaid: { type: Boolean, default: false },
      paidAt: { type: Date },
      collectedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }
    }
  ]
}, { timestamps: true });

// 🔒 Unique: One subscription card per user per year
subscriptionSchema.index({ club: 1, year: 1, user: 1 }, { unique: true });

module.exports = mongoose.model("Subscription", subscriptionSchema);